-- Migration: add_supplier_invoice_items_vat_code
-- No-op: vat_code column on supplier_invoice_items is included in
-- migration 025 (supplier_invoices) in this consolidated set.
-- Originally applied to production as a separate migration.
